In [37]:
import numpy as np

# Example dataset: 3 columns, 6 rows
dataset = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [1, 2, 3],
                    [1, 2, 9],
                    [1, 2, 3],
                    [4, 5, 6]])

unique_all, indices_all = np.unique(dataset, axis=0, return_counts=True)
display(unique_all, indices_all)

unique_all2, indices_all2 = np.unique(unique_all[:,:2], axis=0, return_counts=True)
display(unique_all2, indices_all2)

array([[1, 2, 3],
       [1, 2, 9],
       [4, 5, 6]])

array([3, 1, 2])

array([[1, 2],
       [4, 5]])

array([2, 1])

In [27]:
a = np.array([1,2,3,4,5])
a[[2,4,2,2]]

array([3, 5, 3, 3])